[package]
name = "iocost-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
json = "0.12"
linkify = "0.8"
md5 = "0.7"
octocrab = "0.15"
reqwest = { version= "0.11", features = ["blocking"] }
tempfile = "3.2"
